# DO NOT MODIFY: Auto-generated by the gen_installer.py script from the .github/workflows/build.yml Github Action

$env:REPOSITORY_OWNER = "krupkat"
$env:TARGET_REPO = "xpano"


git clone https://github.com/krupkat/xpano.git xpano --depth 1 --branch v0.1.0
cd xpano
git submodule update --init
cd ..


$env:TAG = "v0.1.0"

cd $env:TARGET_REPO
./misc/build/build-windows-latest.ps1
cd ..
$release_filename = "$env:TARGET_REPO-$env:TAG-windows-x64.zip"
Compress-Archive -Path install/* -DestinationPath $release_filename
Write-Output "::set-output name=release_filename::$release_filename"
cd ..

$env:RELEASE_FILENAME = "$release_filename"

cd $env:TARGET_REPO
(Get-FileHash $env:RELEASE_FILENAME -Algorithm SHA256).Hash | Out-File "${env:RELEASE_FILENAME}.sha256"
Write-Output "Release name: $env:RELEASE_FILENAME"
Write-Output "sha256 checksum: $(Get-Content  "${env:RELEASE_FILENAME}.sha256")"
cd ..

pip install -r requirements.txt
$env:RELEASE_FILENAME = "$release_filename"
$env:SECRET_TOKEN = "$SECRET_TOKEN"
$env:TAG = "v0.1.0"

cd $env:TARGET_REPO
python ../upload_assets.py --repo $env:TARGET_REPO --tag $env:TAG $env:RELEASE_FILENAME "${env:RELEASE_FILENAME}.sha256"
